- name: Installing PostgreSQL
  hosts: db_servers
  become: yes

  tasks:
    - name: Step 1 - Installing ACL
      apt:
        name: acl
        state: present
        update_cache: yes

    - name: Step 2 - Installing PostgreSQL
      apt:
        name: 
          - postgresql
          - postgresql-contrib
        state: present

    - name: Step 3 - Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: yes
